apiVersion: apps/v1
kind: Deployment
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskapp-server
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30000